spring:
  graphql:
    graphiql:
      enabled: true
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driverClassName: org.h2.Driver
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
      path: /h2-console